language: python
python:

- '3.4'

- '3.5'

- '3.6'

- '3.7'

install:
- pip install --upgrade pip
- pip install .[dev]
before_script:
- flake8 weighted_choice
- flake8 tests
script: pytest tests
deploy:
  provider: pypi
  user: dusktreader
  password:
    secure: "This needs to be replaced by running `travis-encrypt` from pip"
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: dusktreader/weighted-choice
    python: 3.6
